spring:
  application:
    name: wallet

  datasource:
    url: jdbc:h2:mem:walletdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  security:
    enabled: true

config-params:
  openedEndpointRoutes:
    - /api/authenticate
    - /swagger-ui/**
    - /swagger/**
    - /v3/api-docs/**
    - /actuator/health
    - /actuator/info

resilience4j:
  circuitbreaker:
    instances:
      walletService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        slidingWindowSize: 10

  retry:
    instances:
      walletService:
        maxAttempts: 3
        waitDuration: 2000
        retryExceptions: java.lang.Exception

#management:
#  endpoint:
#    health:
#      group:
#        default:
#          include: health,info